import { NextResponse } from 'next/server'
import { randomBytes, randomUUID } from 'crypto'
import { and, asc, eq } from 'drizzle-orm'
import { db } from '@/lib/db'
import { werewolfPlayers, werewolfRooms } from '@/lib/db/schema'

const NIGHT_ORDER = ['Mason','Werewolf','Minion','Seer','Apprentice Seer','Robber','Witch','Troublemaker','Drunk','Insomniac']
const rolePool = ['Werewolf','Werewolf','Seer','Robber','Troublemaker','Drunk','Insomniac','Mason','Mason','Hunter','Tanner','Minion','Apprentice Seer','Witch','Villager','Villager','Villager']
const ROLE_ART: Record<string,string> = { Werewolf:'/roles/werewolf.png', Seer:'/roles/seer.png', Tanner:'/roles/tanner.png', Villager:'/roles/villager.png' }
const makeToken = () => randomBytes(18).toString('hex')
const makeCode = () => randomBytes(3).toString('hex').toUpperCase()
const shuffle = <T,>(items: T[]) => [...items].sort(() => Math.random() - 0.5)
async function getRoom(code: string) { return (await db.select().from(werewolfRooms).where(eq(werewolfRooms.code, code)).limit(1))[0] }
async function getPlayer(roomId: string, token: string) { return (await db.select().from(werewolfPlayers).where(and(eq(werewolfPlayers.roomId, roomId), eq(werewolfPlayers.token, token))).limit(1))[0] }
async function nextRole(roomId: string, current: string|null) { const all=await db.select().from(werewolfPlayers).where(eq(werewolfPlayers.roomId,roomId)); const start=Math.max(-1,NIGHT_ORDER.indexOf(current||'')); return NIGHT_ORDER.slice(start+1).find((r)=>all.some((p)=>p.role===r))||null }
async function payload(code: string, token?: string) {
  const room=await getRoom(code); if(!room)return null; const rows=await db.select().from(werewolfPlayers).where(eq(werewolfPlayers.roomId,room.id)).orderBy(asc(werewolfPlayers.seat)); const me=rows.find((p)=>p.token===token)
  const started=room.actionStartedAt?new Date(room.actionStartedAt).getTime():Date.now(); const remaining=room.status==='playing'&&room.phase==='night'?Math.max(0,room.actionSeconds-Math.floor((Date.now()-started)/1000)):room.actionSeconds
  return {code:room.code,status:room.status,phase:room.phase,actionSeconds:room.actionSeconds,activeRole:room.activeRole,actionStartedAt:room.actionStartedAt,remainingSeconds:remaining,centerRoles:room.phase==='results'?room.centerRoles:[],me:me?{id:me.id,name:room.phase==='lobby'?me.name:'You',isHost:me.isHost,startingRole:me.startingRole,finalRole:room.phase==='results'?me.role:null,roleArt:me.role?ROLE_ART[me.role]||'/roles/role-cards.png':null,nightAction:room.phase==='results'&&me.token===token?me.nightAction:null}:null,players:rows.map((p)=>({id:p.id,name:room.phase==='lobby'?p.name:'Player',isHost:p.isHost,isMe:p.token===token,seat:p.seat,hasActed:Boolean(p.nightAction),hasVoted:Boolean(p.voteFor),role:room.phase==='results'||p.token===token?p.role:null,startingRole:p.token===token?p.startingRole:room.phase==='results'?p.startingRole:null,roleArt:(room.phase==='results'||p.token===token)&&p.role?(ROLE_ART[p.role]||'/roles/role-cards.png'):null}))}
}
export async function GET(request:Request){const {searchParams}=new URL(request.url);const code=searchParams.get('code')?.toUpperCase();const token=searchParams.get('token')||undefined;if(!code)return NextResponse.json({error:'Missing room code.'},{status:400});const current=await getRoom(code);if(current?.phase==='night'&&!current.activeRole){const first=await nextRole(current.id,null);await db.update(werewolfRooms).set(first?{activeRole:first,actionStartedAt:new Date(),updatedAt:new Date()}:{phase:'discussion',activeRole:null,actionStartedAt:null,updatedAt:new Date()}).where(eq(werewolfRooms.id,current.id))}else if(current?.phase==='night'&&current.actionStartedAt&&Date.now()-new Date(current.actionStartedAt).getTime()>=current.actionSeconds*1000){const next=await nextRole(current.id,current.activeRole);await db.update(werewolfRooms).set(next?{activeRole:next,actionStartedAt:new Date(),updatedAt:new Date()}:{phase:'discussion',activeRole:null,actionStartedAt:null,updatedAt:new Date()}).where(eq(werewolfRooms.id,current.id))}const data=await payload(code,token);return data?NextResponse.json(data):NextResponse.json({error:'Room not found.'},{status:404})}
export async function POST(request:Request){return mutate(await request.json())}
export async function PATCH(request:Request){return mutate(await request.json())}
async function mutate(body:any){const action=body.action; if(action==='create'){const token=makeToken();let code=makeCode();while(await getRoom(code))code=makeCode();const roomId=randomUUID();await db.insert(werewolfRooms).values({id:roomId,code,hostToken:token,centerRoles:[],deckRoles:[],actionSeconds:30,activeRole:null,actionStartedAt:null,status:'lobby',phase:'lobby',updatedAt:new Date()});await db.insert(werewolfPlayers).values({id:randomUUID(),roomId,token,name:String(body.name||'Host').trim().slice(0,24)||'Host',seat:1,isHost:true});return NextResponse.json({code,token})}
 const code=String(body.code||'').trim().toUpperCase(),room=await getRoom(code);if(!room)return NextResponse.json({error:'Room not found.'},{status:404});const token=String(body.token||''),player=await getPlayer(room.id,token)
 if(action==='join'){const current=await db.select().from(werewolfPlayers).where(eq(werewolfPlayers.roomId,room.id));if(current.length>=10)return NextResponse.json({error:'This game supports up to 10 players.'},{status:400});const joinToken=makeToken();await db.insert(werewolfPlayers).values({id:randomUUID(),roomId:room.id,token:joinToken,name:String(body.name||'Player').trim().slice(0,24)||'Player',seat:current.length+1,isHost:false});return NextResponse.json({code,token:joinToken})}
 if(!player)return NextResponse.json({error:'Player not found.'},{status:403})
 if(action==='settings'){if(!player.isHost||room.phase!=='lobby')return NextResponse.json({error:'Host only in lobby.'},{status:403});const seconds=Math.min(120,Math.max(10,Number(body.seconds)||30));await db.update(werewolfRooms).set({actionSeconds:seconds,updatedAt:new Date()}).where(eq(werewolfRooms.id,room.id));return NextResponse.json({ok:true})}
 if(action==='start'){if(!player.isHost)return NextResponse.json({error:'Only the host can start.'},{status:403});const players=await db.select().from(werewolfPlayers).where(eq(werewolfPlayers.roomId,room.id)).orderBy(asc(werewolfPlayers.seat));if(players.length<3)return NextResponse.json({error:'You need at least 3 players.'},{status:400});const deck=shuffle(rolePool).slice(0,players.length+3);for(let i=0;i<players.length;i++)await db.update(werewolfPlayers).set({startingRole:deck[i],role:deck[i],nightAction:null,voteFor:null}).where(eq(werewolfPlayers.id,players[i].id));const first=NIGHT_ORDER.find((r)=>players.some((p)=>deck[players.indexOf(p)]===r))||'Werewolf';await db.update(werewolfRooms).set({status:'playing',phase:'night',centerRoles:deck.slice(players.length),deckRoles:deck,activeRole:first,actionStartedAt:new Date(),updatedAt:new Date()}).where(eq(werewolfRooms.id,room.id));return NextResponse.json({ok:true})}
 if(action==='advance'){if(!player.isHost)return NextResponse.json({error:'Only the host can advance.'},{status:403});if(room.phase==='night'){const next=await nextRole(room.id,room.activeRole);await db.update(werewolfRooms).set(next?{activeRole:next,actionStartedAt:new Date(),updatedAt:new Date()}:{phase:'discussion',activeRole:null,actionStartedAt:null,updatedAt:new Date()}).where(eq(werewolfRooms.id,room.id))}else if(room.phase==='discussion')await db.update(werewolfRooms).set({phase:'vote',updatedAt:new Date()}).where(eq(werewolfRooms.id,room.id));return NextResponse.json({ok:true})}
 if(action==='night'){if(room.phase!=='night'||room.activeRole!==player.role)return NextResponse.json({error:'It is not your turn.'},{status:400});const elapsed=(Date.now()-new Date(room.actionStartedAt||Date.now()).getTime())/1000;if(elapsed>room.actionSeconds)return NextResponse.json({error:'Your turn expired.'},{status:400});await db.update(werewolfPlayers).set({nightAction:{type:player.role,target:body.target,target2:body.target2,center:body.center}}).where(eq(werewolfPlayers.id,player.id));return NextResponse.json({ok:true})}
 if(action==='finish-night'){if(room.phase!=='night'||room.activeRole!==player.role)return NextResponse.json({error:'It is not your turn.'},{status:400});if(!player.nightAction)return NextResponse.json({error:'Choose an action first.'},{status:400});const next=await nextRole(room.id,room.activeRole);await db.update(werewolfRooms).set(next?{activeRole:next,actionStartedAt:new Date(),updatedAt:new Date()}:{phase:'discussion',activeRole:null,actionStartedAt:null,updatedAt:new Date()}).where(eq(werewolfRooms.id,room.id));return NextResponse.json({ok:true})}
 return NextResponse.json({error:'Unknown action.'},{status:400})}
