import { NextResponse } from 'next/server'
import { randomBytes, randomUUID } from 'crypto'
import { and, asc, eq } from 'drizzle-orm'
import { db } from '@/lib/db'
import { werewolfPlayers, werewolfRooms } from '@/lib/db/schema'

const NIGHT_ORDER=['Mason','Werewolf','Minion','Seer','Apprentice Seer','Robber','Witch','Troublemaker','Drunk','Insomniac']
const rolePool=['Werewolf','Werewolf','Seer','Robber','Troublemaker','Drunk','Insomniac','Mason','Mason','Hunter','Tanner','Minion','Apprentice Seer','Witch','Villager','Villager','Villager']
const ROLE_ART:Record<string,string>={Werewolf:'/roles/werewolf.png',Seer:'/roles/seer.png',Tanner:'/roles/tanner.png',Villager:'/roles/villager.png'}
const makeToken=()=>randomBytes(18).toString('hex'); const makeCode=()=>randomBytes(3).toString('hex').toUpperCase(); const shuffle=<T,>(a:T[])=>[...a].sort(()=>Math.random()-.5)
async function getRoom(code:string){return(await db.select().from(werewolfRooms).where(eq(werewolfRooms.code,code)).limit(1))[0]}
async function getPlayer(roomId:string,token:string){return(await db.select().from(werewolfPlayers).where(and(eq(werewolfPlayers.roomId,roomId),eq(werewolfPlayers.token,token))).limit(1))[0]}
async function nextRole(roomId:string,current:string|null){const all=await db.select().from(werewolfPlayers).where(eq(werewolfPlayers.roomId,roomId));const i=Math.max(-1,NIGHT_ORDER.indexOf(current||''));return NIGHT_ORDER.slice(i+1).find(r=>all.some(p=>p.startingRole===r))||null}
function centerCards(room:any){return Array.isArray(room.centerRoles)?[...room.centerRoles] as string[]:[]}
async function payload(code:string,token?:string){const room=await getRoom(code);if(!room)return null;const rows=await db.select().from(werewolfPlayers).where(eq(werewolfPlayers.roomId,room.id)).orderBy(asc(werewolfPlayers.seat));const me=rows.find(p=>p.token===token);const started=room.actionStartedAt?new Date(room.actionStartedAt).getTime():Date.now();const remaining=room.phase==='night'?Math.max(0,room.actionSeconds-Math.floor((Date.now()-started)/1000)):room.actionSeconds;const privateAction=me?.nightAction as any
 return {code:room.code,status:room.status,phase:room.phase,actionSeconds:room.actionSeconds,activeRole:room.activeRole,actionStartedAt:room.actionStartedAt,remainingSeconds:remaining,centerRoles:room.phase==='results'?room.centerRoles:[],me:me?{id:me.id,name:room.phase==='lobby'?me.name:'You',isHost:me.isHost,startingRole:me.startingRole,finalRole:room.phase==='results'?me.role:null,roleArt:me.role?ROLE_ART[me.role]||'/roles/role-cards.png':null,nightAction:privateAction||null}:null,players:rows.map(p=>({id:p.id,name:room.phase==='lobby'?p.name:'Player',isHost:p.isHost,isMe:p.token===token,seat:p.seat,hasActed:Boolean(p.nightAction),hasVoted:Boolean(p.voteFor),role:room.phase==='results'||p.token===token?p.role:null,startingRole:p.token===token?p.startingRole:room.phase==='results'?p.startingRole:null,roleArt:(room.phase==='results'||p.token===token)&&p.role?(ROLE_ART[p.role]||'/roles/role-cards.png'):null}))}
}
async function advanceNight(room:any){const next=await nextRole(room.id,room.activeRole);await db.update(werewolfRooms).set(next?{activeRole:next,actionStartedAt:new Date(),updatedAt:new Date()}:{phase:'discussion',activeRole:null,actionStartedAt:null,updatedAt:new Date()}).where(eq(werewolfRooms.id,room.id))}
export async function GET(request:Request){const {searchParams}=new URL(request.url);const code=searchParams.get('code')?.toUpperCase();const token=searchParams.get('token')||undefined;if(!code)return NextResponse.json({error:'Missing room code.'},{status:400});const room=await getRoom(code);if(room?.phase==='night'&&(!room.activeRole||(room.actionStartedAt&&Date.now()-new Date(room.actionStartedAt).getTime()>=room.actionSeconds*1000)))await advanceNight(room);const data=await payload(code,token);return data?NextResponse.json(data):NextResponse.json({error:'Room not found.'},{status:404})}
export async function POST(request:Request){return mutate(await request.json())} export async function PATCH(request:Request){return mutate(await request.json())}
async function mutate(body:any){const action=body.action;if(action==='create'){const token=makeToken();let code=makeCode();while(await getRoom(code))code=makeCode();const roomId=randomUUID();await db.insert(werewolfRooms).values({id:roomId,code,hostToken:token,centerRoles:[],deckRoles:[],actionSeconds:30,activeRole:null,actionStartedAt:null,status:'lobby',phase:'lobby',updatedAt:new Date()});await db.insert(werewolfPlayers).values({id:randomUUID(),roomId,token,name:String(body.name||'Host').trim().slice(0,24)||'Host',seat:1,isHost:true});return NextResponse.json({code,token})}
 const code=String(body.code||'').trim().toUpperCase(),room=await getRoom(code);if(!room)return NextResponse.json({error:'Room not found.'},{status:404});const token=String(body.token||''),player=await getPlayer(room.id,token)
 if(action==='join'){const current=await db.select().from(werewolfPlayers).where(eq(werewolfPlayers.roomId,room.id));if(current.length>=10)return NextResponse.json({error:'This game supports up to 10 players.'},{status:400});const joinToken=makeToken();await db.insert(werewolfPlayers).values({id:randomUUID(),roomId:room.id,token:joinToken,name:String(body.name||'Player').trim().slice(0,24)||'Player',seat:current.length+1,isHost:false});return NextResponse.json({code,token:joinToken})}
 if(!player)return NextResponse.json({error:'Player not found.'},{status:403})
 if(action==='settings'){if(!player.isHost||room.phase!=='lobby')return NextResponse.json({error:'Host only in lobby.'},{status:403});await db.update(werewolfRooms).set({actionSeconds:Math.min(120,Math.max(10,Number(body.seconds)||30)),updatedAt:new Date()}).where(eq(werewolfRooms.id,room.id));return NextResponse.json({ok:true})}
 if(action==='start'){if(!player.isHost)return NextResponse.json({error:'Only the host can start.'},{status:403});const players=await db.select().from(werewolfPlayers).where(eq(werewolfPlayers.roomId,room.id)).orderBy(asc(werewolfPlayers.seat));if(players.length<3)return NextResponse.json({error:'You need at least 3 players.'},{status:400});const deck=shuffle(rolePool).slice(0,players.length+3);for(let i=0;i<players.length;i++)await db.update(werewolfPlayers).set({startingRole:deck[i],role:deck[i],nightAction:null,voteFor:null}).where(eq(werewolfPlayers.id,players[i].id));const first=NIGHT_ORDER.find(r=>players.some((_,i)=>deck[i]===r))||null;await db.update(werewolfRooms).set({status:'playing',phase:first?'night':'discussion',centerRoles:deck.slice(players.length),deckRoles:deck,activeRole:first,actionStartedAt:first?new Date():null,updatedAt:new Date()}).where(eq(werewolfRooms.id,room.id));return NextResponse.json({ok:true})}
 if(action==='advance'){if(!player.isHost)return NextResponse.json({error:'Only the host can advance.'},{status:403});if(room.phase==='night')await advanceNight(room);else if(room.phase==='discussion')await db.update(werewolfRooms).set({phase:'vote',updatedAt:new Date()}).where(eq(werewolfRooms.id,room.id));return NextResponse.json({ok:true})}
 if(action==='night'){if(room.phase!=='night'||room.activeRole!==player.startingRole)return NextResponse.json({error:'It is not your turn.'},{status:400});if((Date.now()-new Date(room.actionStartedAt||Date.now()).getTime())/1000>room.actionSeconds)return NextResponse.json({error:'Your turn expired.'},{status:400});const players=await db.select().from(werewolfPlayers).where(eq(werewolfPlayers.roomId,room.id)).orderBy(asc(werewolfPlayers.seat));const centers=centerCards(room);const target=players.find(p=>p.id===body.target);const target2=players.find(p=>p.id===body.target2);let result:any={type:player.startingRole,target:body.target,target2:body.target2,center:body.center};
  if(player.startingRole==='Seer'){if(body.mode==='player'&&target)result.peek=[target.role];else if(body.mode==='center'&&body.center&&body.center2)result.peek=[centers[Number(body.center)],centers[Number(body.center2)]];else return NextResponse.json({error:'Choose one player or two center cards.'},{status:400})}
  if(player.startingRole==='Robber'){if(!target||target.id===player.id)return NextResponse.json({error:'Choose another player.'},{status:400});result.peek=[target.role];await db.update(werewolfPlayers).set({role:target.role}).where(eq(werewolfPlayers.id,player.id));await db.update(werewolfPlayers).set({role:player.role}).where(eq(werewolfPlayers.id,target.id))}
  if(player.startingRole==='Troublemaker'){if(!target||!target2||target.id===target2.id||target.id===player.id||target2.id===player.id)return NextResponse.json({error:'Choose two other players.'},{status:400});await db.update(werewolfPlayers).set({role:target2.role}).where(eq(werewolfPlayers.id,target.id));await db.update(werewolfPlayers).set({role:target.role}).where(eq(werewolfPlayers.id,target2.id))}
  if(player.startingRole==='Drunk'){if(body.center===undefined)return NextResponse.json({error:'Choose a center card.'},{status:400});const c=centers[Number(body.center)];centers[Number(body.center)]=player.role!;await db.update(werewolfPlayers).set({role:c}).where(eq(werewolfPlayers.id,player.id));await db.update(werewolfRooms).set({centerRoles:centers}).where(eq(werewolfRooms.id,room.id))}
  if(player.startingRole==='Witch'){if(body.center===undefined)return NextResponse.json({error:'Look at a center card first.'},{status:400});const oldCenter=centers[Number(body.center)];result.peek=[oldCenter];if(target){centers[Number(body.center)]=target.role!;await db.update(werewolfPlayers).set({role:oldCenter}).where(eq(werewolfPlayers.id,target.id));await db.update(werewolfRooms).set({centerRoles:centers}).where(eq(werewolfRooms.id,room.id))}}
  if(player.startingRole==='Werewolf'&&body.center!==undefined){result.peek=[centers[Number(body.center)]]}
  if(player.startingRole==='Apprentice Seer'&&body.center!==undefined)result.peek=[centers[Number(body.center)]]
  if(player.startingRole==='Mason')result.peek=players.filter(p=>p.id!==player.id&&p.role==='Mason').map(p=>p.name)
  if(player.startingRole==='Insomniac')result.peek=[player.role]
  await db.update(werewolfPlayers).set({nightAction:result}).where(eq(werewolfPlayers.id,player.id));return NextResponse.json({ok:true})}
 if(action==='finish-night'){if(room.phase!=='night'||room.activeRole!==player.startingRole)return NextResponse.json({error:'It is not your turn.'},{status:400});if(!player.nightAction)return NextResponse.json({error:'Complete your action first.'},{status:400});await advanceNight(room);return NextResponse.json({ok:true})}
 if(action==='vote'){if(room.phase!=='vote'||player.voteFor)return NextResponse.json({error:'Vote unavailable.'},{status:400});await db.update(werewolfPlayers).set({voteFor:body.target||null}).where(eq(werewolfPlayers.id,player.id));const all=await db.select().from(werewolfPlayers).where(eq(werewolfPlayers.roomId,room.id));if(all.every(p=>p.voteFor))await db.update(werewolfRooms).set({phase:'results',updatedAt:new Date()}).where(eq(werewolfRooms.id,room.id));return NextResponse.json({ok:true})}
 return NextResponse.json({error:'Unknown action.'},{status:400})}
export function art(role:string){return ROLE_ART[role]||'/roles/role-cards.png'}
