import { NextResponse } from 'next/server'
import { randomBytes, randomUUID } from 'crypto'
import { and, asc, eq } from 'drizzle-orm'
import { db } from '@/lib/db'
import { werewolfPlayers, werewolfRooms } from '@/lib/db/schema'

const rolePool = ['Werewolf','Werewolf','Seer','Robber','Troublemaker','Drunk','Insomniac','Mason','Mason','Hunter','Tanner','Minion','Apprentice Seer','Witch','Villager','Villager','Villager']
const makeToken = () => randomBytes(18).toString('hex')
const makeCode = () => randomBytes(3).toString('hex').toUpperCase()
const shuffle = <T,>(items: T[]) => [...items].sort(() => Math.random() - 0.5)
async function getRoom(code: string) { return (await db.select().from(werewolfRooms).where(eq(werewolfRooms.code, code)).limit(1))[0] }
async function getPlayer(roomId: string, token: string) { return (await db.select().from(werewolfPlayers).where(and(eq(werewolfPlayers.roomId, roomId), eq(werewolfPlayers.token, token))).limit(1))[0] }
async function payload(code: string, token?: string) {
  const room = await getRoom(code); if (!room) return null
  const rows = await db.select().from(werewolfPlayers).where(eq(werewolfPlayers.roomId, room.id)).orderBy(asc(werewolfPlayers.seat))
  const me = rows.find((p) => p.token === token)
  const counts = rows.reduce<Record<string,number>>((acc, p) => { if (p.voteFor) acc[p.voteFor] = (acc[p.voteFor] || 0) + 1; return acc }, {})
  const highest = Math.max(0, ...Object.values(counts))
  const eliminated = room.phase === 'results' ? rows.filter((p) => highest > 0 && counts[p.id] === highest) : []
  const hunterTargets = eliminated.filter((p) => p.role === 'Hunter').map((p) => p.voteFor).filter(Boolean) as string[]
  const allEliminatedIds = [...new Set([...eliminated.map((p) => p.id), ...hunterTargets])]
  const dead = rows.filter((p) => allEliminatedIds.includes(p.id))
  const tannerWins = dead.some((p) => p.role === 'Tanner')
  const wolfKilled = dead.some((p) => p.role === 'Werewolf' || p.role === 'Alpha Werewolf')
  const outcome = room.phase === 'results' ? (tannerWins ? 'Tanner wins alone.' : wolfKilled ? 'Village wins.' : 'Werewolves win.') : null
  return { ...room, centerRoles: room.phase === 'results' ? room.centerRoles : [], eliminatedIds: allEliminatedIds, outcome, players: rows.map((p) => ({ id:p.id, name:p.name, seat:p.seat, isHost:p.isHost, isMe:p.token===token, role: room.phase === 'results' || p.token===token ? p.role : null, startingRole: p.token===token ? p.startingRole : room.phase === 'results' ? p.startingRole : null, hasActed:Boolean(p.nightAction), hasVoted:Boolean(p.voteFor), nightAction: room.phase === 'results' && p.token===token ? p.nightAction : null, voteFor: room.phase === 'results' ? p.voteFor : null })), myStartingRole: me?.startingRole, myFinalRole: me?.role }
}
export async function POST(request: Request) {
  const body = await request.json(); const name = String(body.name || '').trim().slice(0,24); if (!name) return NextResponse.json({error:'Enter a display name.'},{status:400})
  if (body.action === 'create') { const token=makeToken(); let code=makeCode(); while(await getRoom(code)) code=makeCode(); const roomId=randomUUID(); await db.insert(werewolfRooms).values({id:roomId,code,hostToken:token,centerRoles:[],deckRoles:[]}); await db.insert(werewolfPlayers).values({id:randomUUID(),roomId,token,name,seat:1,isHost:true}); return NextResponse.json({code,token}) }
  const code=String(body.code||'').trim().toUpperCase(); const room=await getRoom(code); if(!room)return NextResponse.json({error:'That room code does not exist.'},{status:404}); const current=await db.select().from(werewolfPlayers).where(eq(werewolfPlayers.roomId,room.id)); if(current.length>=10)return NextResponse.json({error:'This game supports up to 10 players.'},{status:400}); const token=makeToken(); await db.insert(werewolfPlayers).values({id:randomUUID(),roomId:room.id,token,name,seat:current.length+1}); return NextResponse.json({code,token})
}
export async function GET(request: Request) { const {searchParams}=new URL(request.url); const code=searchParams.get('code')?.toUpperCase(); const token=searchParams.get('token')||undefined; if(!code)return NextResponse.json({error:'Missing room code.'},{status:400}); const data=await payload(code,token); return data?NextResponse.json(data):NextResponse.json({error:'Room not found.'},{status:404}) }
export async function PATCH(request: Request) {
  const body=await request.json(); const code=String(body.code||'').toUpperCase(); const token=String(body.token||''); const room=await getRoom(code); if(!room)return NextResponse.json({error:'Room not found.'},{status:404}); const player=await getPlayer(room.id,token); if(!player)return NextResponse.json({error:'Player not found.'},{status:403})
  if(body.action==='start') { if(!player.isHost)return NextResponse.json({error:'Only the host can start the game.'},{status:403}); const players=await db.select().from(werewolfPlayers).where(eq(werewolfPlayers.roomId,room.id)).orderBy(asc(werewolfPlayers.seat)); if(players.length<3)return NextResponse.json({error:'You need at least 3 players.'},{status:400}); const deck=shuffle(rolePool).slice(0,players.length+3); for(let i=0;i<players.length;i++)await db.update(werewolfPlayers).set({startingRole:deck[i],role:deck[i],nightAction:null,voteFor:null}).where(eq(werewolfPlayers.id,players[i].id)); await db.update(werewolfRooms).set({status:'playing',phase:'reveal',centerRoles:deck.slice(players.length),deckRoles:deck,updatedAt:new Date()}).where(eq(werewolfRooms.id,room.id)); return NextResponse.json({ok:true}) }
  if(body.action==='advance') { if(!player.isHost)return NextResponse.json({error:'Only the host can advance the phase.'},{status:403}); const next=room.phase==='reveal'?'night':room.phase==='night'?'discussion':room.phase==='discussion'?'vote':'results'; if(room.phase==='night'&&next==='discussion'){ const rows=await db.select().from(werewolfPlayers).where(eq(werewolfPlayers.roomId,room.id)); const actions=rows.map(r=>({id:r.id,action:r.nightAction})); const center=[...(room.centerRoles as string[])]; const byId=new Map(rows.map(r=>[r.id,r])); const swap=(a:string,b:string)=>{const pa=byId.get(a),pb=byId.get(b);if(!pa||!pb)return;const ar=pa.role;pa.role=pb.role;pb.role=ar}; for(const item of actions){const a=item.action as {type?:string;target?:string;target2?:string;center?:string}|null;if(!a)continue; const p=byId.get(item.id); if(!p)continue; if(a.type==='Robber'&&a.target){swap(p.id,a.target);p.nightAction={...a,newRole:p.role}} if(a.type==='Troublemaker'&&a.target&&a.target2)swap(a.target,a.target2); if(a.type==='Drunk'&&a.center){const idx=Number(a.center);if(center[idx]){const old=p.role;p.role=center[idx];center[idx]=old}} if(a.type==='Witch'&&a.center&&a.target){const idx=Number(a.center);if(center[idx]){const old=byId.get(a.target)?.role; if(old){byId.get(a.target)!.role=center[idx];center[idx]=old}}} } for(const p of rows)await db.update(werewolfPlayers).set({role:p.role,nightAction:p.nightAction}).where(eq(werewolfPlayers.id,p.id)); await db.update(werewolfRooms).set({centerRoles:center,updatedAt:new Date()}).where(eq(werewolfRooms.id,room.id)) }
    await db.update(werewolfRooms).set({phase:next,updatedAt:new Date()}).where(eq(werewolfRooms.id,room.id)); return NextResponse.json({ok:true}) }
  if(body.action==='night') { if(room.phase!=='night')return NextResponse.json({error:'Night actions are closed.'},{status:400}); const target=body.target?String(body.target):undefined; const target2=body.target2?String(body.target2):undefined; const center=body.center===undefined?undefined:String(body.center); const allowed=['Werewolf','Seer','Robber','Troublemaker','Drunk','Insomniac','Mason','Minion','Apprentice Seer','Witch','Alpha Werewolf']; if(!allowed.includes(player.role||''))return NextResponse.json({ok:true}); await db.update(werewolfPlayers).set({nightAction:{type:player.role,target,target2,center}}).where(eq(werewolfPlayers.id,player.id)); return NextResponse.json({ok:true}) }
  if(body.action==='vote') { if(room.phase!=='vote')return NextResponse.json({error:'Voting is closed.'},{status:400}); const target=String(body.target||''); if(!target||target===player.id)return NextResponse.json({error:'Choose another player.'},{status:400}); await db.update(werewolfPlayers).set({voteFor:target}).where(eq(werewolfPlayers.id,player.id)); return NextResponse.json({ok:true}) }
  return NextResponse.json({error:'Unknown action.'},{status:400})
}
