'use client'

import { useCallback, useEffect, useState } from 'react'
import { Copy, Moon, Shield, Sparkles, Users, Wand2, Eye, Vote, MessageCircle, ArrowRight } from 'lucide-react'

type Player = { id: string; name: string; seat: number; isHost: boolean; isMe?: boolean; role?: string | null; hasActed?: boolean; hasVoted?: boolean }
type Room = { code: string; status: string; phase: string; players: Player[]; centerRoles: string[] }
const roleInfo: Record<string, { icon: string; tone: string; text: string }> = { Werewolf: { icon: '☾', tone: 'red', text: 'Choose someone to hunt tonight.' }, Seer: { icon: '◈', tone: 'violet', text: 'Inspect one player or two center cards.' }, Robber: { icon: '↔', tone: 'gold', text: 'Swap with another player, then see your new role.' }, Troublemaker: { icon: '✦', tone: 'blue', text: 'Swap two other players without looking.' }, Villager: { icon: '○', tone: 'green', text: 'Sleep through the night. Trust your instincts.' }, Drunk: { icon: '◇', tone: 'gold', text: 'Swap your card with a center card.' }, Insomniac: { icon: '◌', tone: 'violet', text: 'Check your role again before dawn.' } }

export default function Page() {
  const [name, setName] = useState(''); const [codeInput, setCodeInput] = useState(''); const [room, setRoom] = useState<Room | null>(null); const [token, setToken] = useState(''); const [mode, setMode] = useState<'home'|'join'|'room'>('home'); const [error, setError] = useState(''); const [copied, setCopied] = useState(false); const [selected, setSelected] = useState('')
  const enterRoom = useCallback(async (action: 'create'|'join') => { setError(''); const r = await fetch('/api/rooms', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({ action, name, code:codeInput }) }); const d=await r.json(); if(!r.ok) return setError(d.error); setToken(d.token); setCodeInput(d.code); setName(name.trim()); setMode('room') }, [codeInput,name])
  useEffect(() => { if(mode!=='room'||!codeInput||!token)return; let active=true; const load=async()=>{const r=await fetch(`/api/rooms?code=${codeInput}&token=${token}`,{cache:'no-store'});if(r.ok&&active)setRoom(await r.json())};load();const i=setInterval(load,1800);return()=>{active=false;clearInterval(i)} },[codeInput,mode,token])
  const act=async(action:string,target?:string)=>{setError('');const r=await fetch('/api/rooms',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({code:codeInput,token,action,target})});const d=await r.json();if(!r.ok)setError(d.error);setSelected('')}
  const me=room?.players.find(p=>p.isMe); const info=roleInfo[me?.role||'Villager']; const copy=async()=>{await navigator.clipboard?.writeText(codeInput);setCopied(true);setTimeout(()=>setCopied(false),1200)}
  return <main className="min-h-screen bg-[#101214] text-[#f4f0e8]"><div className="mx-auto flex min-h-screen max-w-6xl flex-col px-5 py-6 md:px-10"><header className="flex items-center justify-between border-b border-white/10 pb-6"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-full border border-[#e0b867]/50 text-[#e0b867]"><Moon size={19}/></div><div><div className="font-mono text-[10px] uppercase tracking-[.35em] text-[#e0b867]">A night of suspicion</div><div className="font-serif text-xl">ONE NIGHT</div></div></div><div className="hidden items-center gap-2 text-xs text-white/45 sm:flex"><Shield size={14}/> Private rooms. No accounts.</div></header>
  {mode==='home'&&<section className="grid flex-1 items-center gap-12 py-12 lg:grid-cols-[1fr_.8fr]"><div><div className="mb-6 flex items-center gap-2 font-mono text-xs uppercase tracking-[.3em] text-[#e0b867]"><Sparkles size={14}/> Social deduction, simplified</div><h1 className="max-w-xl font-serif text-6xl leading-[.92] tracking-[-.04em] md:text-8xl">Trust no one.<br/><span className="text-[#e0b867]">Especially</span> yourself.</h1><p className="mt-8 max-w-md leading-7 text-white/55">A fast, chaotic round for your next game night. Make a room, share the code, and let the accusations begin.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your display name" className="h-12 rounded-md border border-white/15 bg-white/[.04] px-4 outline-none focus:border-[#e0b867]"/><button onClick={()=>name.trim()&&setMode('join')} className="h-12 rounded-md bg-[#e0b867] px-6 font-mono text-xs font-bold uppercase tracking-widest text-[#101214]">Enter the night</button></div></div><div className="mx-auto w-full max-w-sm rotate-[-3deg] border border-[#e0b867]/40 bg-[#17191c] p-5"><div className="flex aspect-[.72] flex-col justify-between border border-white/10 p-6"><div className="font-mono text-[10px] uppercase tracking-widest text-white/40">Role card · keep secret</div><div className="text-center"><div className="mx-auto mb-6 text-6xl text-[#e0b867]">☾</div><div className="font-serif text-4xl">Werewolf</div><div className="mt-4 text-sm text-white/45">Wake up. Find your pack. Leave no trace.</div></div><div className="font-mono text-[10px] text-white/30">ONE NIGHT / 01</div></div></div></section>}
  {mode==='join'&&<section className="mx-auto flex w-full max-w-lg flex-1 flex-col justify-center py-16"><button onClick={()=>setMode('home')} className="mb-10 w-fit font-mono text-xs uppercase tracking-widest text-white/40">← Back</button><div className="font-mono text-xs uppercase tracking-[.3em] text-[#e0b867]">Join a game</div><h2 className="mt-3 font-serif text-5xl">Where is the pack?</h2><p className="mt-4 text-white/50">Ask the host for their six-character room code.</p><input autoFocus value={codeInput} onChange={e=>setCodeInput(e.target.value.toUpperCase().slice(0,6))} placeholder="ABC123" className="mt-8 h-20 rounded-md border border-white/15 bg-white/[.04] px-5 font-mono text-3xl tracking-[.4em] outline-none focus:border-[#e0b867]"/><button onClick={()=>enterRoom('join')} disabled={codeInput.length<6} className="mt-4 h-14 rounded-md bg-[#e0b867] font-mono text-xs font-bold uppercase tracking-widest text-[#101214] disabled:opacity-40">Join room</button><div className="my-8 flex items-center gap-4 text-xs text-white/25"><span className="h-px flex-1 bg-white/10"/>or<span className="h-px flex-1 bg-white/10"/></div><button onClick={()=>enterRoom('create')} className="h-14 rounded-md border border-white/15 font-mono text-xs uppercase tracking-widest text-white/70">Create a new room</button>{error&&<p className="mt-5 text-sm text-[#e6786b]">{error}</p>}</section>}
  {mode==='room'&&room&&<section className="flex-1 py-10"><div className="flex flex-col justify-between gap-6 border-b border-white/10 pb-8 sm:flex-row sm:items-end"><div><div className="font-mono text-xs uppercase tracking-[.3em] text-[#e0b867]">{room.phase==='lobby'?'Waiting room':room.phase.toUpperCase()}</div><h2 className="mt-3 font-serif text-5xl">{room.phase==='lobby'?'Gather your pack.':room.phase==='reveal'?`Your secret role, ${me?.name}.`:room.phase==='night'?'The village sleeps.':room.phase==='discussion'?'Make your case.':room.phase==='vote'?'Point the finger.':'Dawn has arrived.'}</h2></div><button onClick={copy} className="flex h-14 items-center gap-4 border border-[#e0b867]/50 bg-[#e0b867]/10 px-5 font-mono text-sm tracking-[.3em] text-[#e0b867]">{codeInput}<Copy size={15}/><span className="text-[10px] tracking-normal text-white/40">{copied?'COPIED':'COPY'}</span></button></div>
  {room.phase==='lobby'&&<div className="py-10"><div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-2 font-mono text-xs uppercase tracking-widest text-white/40"><Users size={15}/> {room.players.length} / 12 players</div><span className="font-mono text-xs text-[#e0b867]">{room.players.length<3?'Need 3 to start':'Ready to begin'}</span></div><div className="grid gap-3 sm:grid-cols-2">{room.players.map(p=><div key={p.id} className="flex items-center justify-between border border-white/10 bg-white/[.03] p-4"><span>{p.name}{p.isMe&&<span className="ml-2 text-xs text-white/30">(you)</span>}</span>{p.isHost&&<span className="font-mono text-[10px] uppercase tracking-widest text-[#e0b867]">Host</span>}</div>)}</div>{me?.isHost&&<button onClick={()=>act('start')} disabled={room.players.length<3} className="mt-8 flex h-14 items-center gap-3 bg-[#e0b867] px-7 font-mono text-xs font-bold uppercase tracking-widest text-[#101214] disabled:opacity-35"><Wand2 size={16}/> Start the night</button>}</div>}
  {room.phase==='reveal'&&<GameCard icon={info.icon} role={me?.role||'Villager'} text={info.text}><div className="mt-8 flex justify-end">{me?.isHost&&<button onClick={()=>act('advance')} className="flex items-center gap-3 bg-[#e0b867] px-6 py-4 font-mono text-xs font-bold uppercase tracking-widest text-[#101214]">Begin night <ArrowRight size={15}/></button>}</div></GameCard>}
  {room.phase==='night'&&<PhasePanel icon={<Moon size={18}/>} title="Choose your move" text={info.text} players={room.players} selected={selected} setSelected={setSelected} onAction={()=>act('night',selected||'pass')} acted={Boolean(me?.hasActed)} role={me?.role||''}/>} 
  {room.phase==='discussion'&&<Discussion room={room} isHost={Boolean(me?.isHost)} onAdvance={()=>act('advance')}/>} 
  {room.phase==='vote'&&<PhasePanel icon={<Vote size={18}/>} title="Who do you trust?" text="Vote for the player you believe is the werewolf. You cannot vote for yourself." players={room.players.filter(p=>!p.isMe)} selected={selected} setSelected={setSelected} onAction={()=>act('vote',selected)} acted={Boolean(me?.hasVoted)} role="vote"/>}
  {room.phase==='results'&&<Results room={room}/>} {error&&<p className="mt-6 text-sm text-[#e6786b]">{error}</p>}</section>}
  </div></main>
}
function GameCard({icon,role,text,children}:{icon:string;role:string;text:string;children:React.ReactNode}){return <div className="mx-auto max-w-lg py-12"><div className="border border-[#e0b867]/40 bg-[#17191c] p-6"><div className="flex aspect-[.75] flex-col justify-between border border-white/10 p-8 text-center"><div className="font-mono text-[10px] uppercase tracking-widest text-white/35">Your role is secret</div><div><div className="mb-6 text-6xl text-[#e0b867]">{icon}</div><h3 className="font-serif text-5xl">{role}</h3><p className="mx-auto mt-5 max-w-xs leading-7 text-white/50">{text}</p></div><div className="font-mono text-[10px] uppercase tracking-widest text-white/30">Do not show this card</div></div></div>{children}</div>}
function PhasePanel({icon,title,text,players,selected,setSelected,onAction,acted,role}:{icon:React.ReactNode;title:string;text:string;players:Player[];selected:string;setSelected:(s:string)=>void;onAction:()=>void;acted:boolean;role:string}){return <div className="grid gap-10 py-12 lg:grid-cols-[.8fr_1.2fr]"><div><div className="mb-5 flex items-center gap-3 font-mono text-xs uppercase tracking-widest text-[#e0b867]">{icon} {role==='vote'?'Day vote':'Night action'}</div><h3 className="font-serif text-5xl">{title}</h3><p className="mt-5 leading-7 text-white/50">{text}</p>{acted&&<div className="mt-8 border border-[#86b89a]/30 bg-[#86b89a]/10 p-4 text-sm text-[#a9d4b8]">Choice locked in. Waiting for the rest of the village.</div>}</div><div className="border border-white/10 bg-white/[.03] p-5"><div className="mb-4 font-mono text-[10px] uppercase tracking-widest text-white/35">{role==='vote'?'Choose a suspect':'Choose a player'}</div><div className="grid gap-2">{players.map(p=><button key={p.id} disabled={acted} onClick={()=>setSelected(p.id)} className={`flex items-center justify-between border p-4 text-left transition ${selected===p.id?'border-[#e0b867] bg-[#e0b867]/10':'border-white/10 hover:border-white/30'}`}><span>{p.name}</span><span className="font-mono text-xs text-white/30">seat {p.seat}</span></button>)}</div><button disabled={!selected||acted} onClick={onAction} className="mt-4 h-12 w-full bg-[#e0b867] font-mono text-xs font-bold uppercase tracking-widest text-[#101214] disabled:opacity-35">Lock choice</button></div></div>}
function Discussion({room,isHost,onAdvance}:{room:Room;isHost:boolean;onAdvance:()=>void}){return <div className="grid gap-10 py-12 lg:grid-cols-[1fr_280px]"><div><div className="mb-5 flex items-center gap-3 font-mono text-xs uppercase tracking-widest text-[#e0b867]"><MessageCircle size={18}/> Open discussion</div><h3 className="font-serif text-5xl">Make your case.</h3><p className="mt-5 max-w-xl leading-7 text-white/50">Everyone has a story. Compare what you remember, expose suspicious moves, and decide who is bluffing. This is your only chance to talk before the vote.</p><div className="mt-10 border border-white/10 bg-white/[.03] p-5 text-sm text-white/45">When the table is ready, the host can open voting.</div></div><aside className="border border-white/10 bg-white/[.03] p-6"><div className="font-mono text-[10px] uppercase tracking-widest text-[#e0b867]">Ready check</div><div className="mt-5 space-y-3">{room.players.map(p=><div key={p.id} className="flex justify-between text-sm"><span>{p.name}</span><span className="text-[#86b89a]">online</span></div>)}</div>{isHost&&<button onClick={onAdvance} className="mt-7 flex h-12 w-full items-center justify-center gap-2 bg-[#e0b867] font-mono text-xs font-bold uppercase tracking-widest text-[#101214]">Open voting <ArrowRight size={14}/></button>}</aside></div>}
function Results({room}:{room:Room}){return <div className="py-14"><div className="mb-10 text-center"><div className="font-mono text-xs uppercase tracking-[.3em] text-[#e0b867]">The verdict</div><h3 className="mt-3 font-serif text-6xl">Dawn has arrived.</h3><p className="mt-4 text-white/45">The votes are in. Reveal the truth around the table.</p></div><div className="mx-auto max-w-2xl border border-white/10 bg-white/[.03] p-5">{room.players.map(p=><div key={p.id} className="flex items-center justify-between border-b border-white/10 p-4 last:border-0"><span>{p.name}</span><span className="font-mono text-xs text-white/40">Vote recorded</span></div>)}</div></div>}
